// <auto-generated />
namespace ProjetoORM_EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class version20190819 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(version20190819));
        
        string IMigrationMetadata.Id
        {
            get { return "201908192242480_version20190819"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
