// <auto-generated />
using GerenciamentoFuncionarios.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace GerenciamentoFuncionarios.Migrations
{
    [DbContext(typeof(GerenciamentoFuncionariosContext))]
    [Migration("20191016234400_v2.2")]
    partial class v22
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GerenciamentoFuncionarios.Models.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<int?>("TarefaId");

                    b.HasKey("Id");

                    b.HasIndex("TarefaId");

                    b.ToTable("Departamento");
                });

            modelBuilder.Entity("GerenciamentoFuncionarios.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataNascimento");

                    b.Property<int?>("LotaocaoId");

                    b.Property<string>("Nome");

                    b.Property<int?>("TarefaId");

                    b.HasKey("Id");

                    b.HasIndex("LotaocaoId");

                    b.HasIndex("TarefaId");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("GerenciamentoFuncionarios.Models.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao")
                        .IsRequired();

                    b.Property<DateTime>("Fim");

                    b.Property<DateTime>("Inicio");

                    b.Property<string>("Titulo")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Tarefa");
                });

            modelBuilder.Entity("GerenciamentoFuncionarios.Models.Departamento", b =>
                {
                    b.HasOne("GerenciamentoFuncionarios.Models.Tarefa")
                        .WithMany("Departamentos")
                        .HasForeignKey("TarefaId");
                });

            modelBuilder.Entity("GerenciamentoFuncionarios.Models.Funcionario", b =>
                {
                    b.HasOne("GerenciamentoFuncionarios.Models.Departamento", "Lotaocao")
                        .WithMany("Funcionarios")
                        .HasForeignKey("LotaocaoId");

                    b.HasOne("GerenciamentoFuncionarios.Models.Tarefa")
                        .WithMany("Funcionarios")
                        .HasForeignKey("TarefaId");
                });
#pragma warning restore 612, 618
        }
    }
}
